* The Basics
** DONE Get a blank game up and running
** DONE Draw a square on the screen
** DONE Apply a texture to square
* Make it useful
** DONE Figure out resource management
   I don't really know how to handle resources right now. I want to be able to dynamically add/remove
   them, but it shouldn't rely on the GC, since it's unpredictable and resources can take up quite a
   bit of memory.
   Note: Maybe I should code this The Wrong Way™ first. (wrong way being "load new copies of
   resources into a slot every time, and require manual unloading of each")
   UPDATE: I *think* this is enough. We'll see.
** DONE Write a proper texture system
   It's not complete, no, but it's useful enough.
** DONE Write a sprite prototype
   Everything I need to make a sprite should go into this sprite prototype. When I want
   to start animating stuff, it should all go into this sprite prototype. I'll refactor things out
   later, but first things first. (animation comes later)


* Write the library modules
** graphics module prototypes
*** engine
*** screen   
*** sprite
*** animated sprite
*** animation
*** font
    I want to be able to easily draw text on-screen. Using cl-ftgl might work.
*** particle system
** audio prototypes
*** sample
*** music
