(in-package :until-it-dies)

(defun setup-ortho-projection (width height)
  (gl:matrix-mode :projection)
  (gl:load-identity)
  (gl:viewport 0 0 width height)
  (gl:ortho 0 width 0 height 0 100) ;0,0 is at bottom left of screen. Much nicer for maths.
  (gl:matrix-mode :modelview))

(defun rectangle (x y width height &optional (u1 0) (v1 0) (u2 1) (v2 1))
  (let* ((w/2 (/ width 2.0))
         (h/2 (/ height 2.0))
         (x1 (- x w/2))
         (x2 (+ x w/2))
         (y1 (- y h/2))
         (y2 (+ y h/2)))
    (gl:tex-coord u1 v2)
    (gl:vertex x1 y1 0)
    (gl:tex-coord u2 v2)
    (gl:vertex x2 y1 0)
    (gl:tex-coord u2 v1)
    (gl:vertex x2 y2 0)
    (gl:tex-coord u1 v1)
    (gl:vertex x1 y2 0)))